### PR TITLE
fix[tutorial/chess] - king Castling

### PR DESCRIPTION
**Pull request by sangramsingh-kss**
Update Rooks position on castling move.
- Declare winners/draws
- Reset board on Game end.

Resolves: #91

### CODE REVIEW

**Comment by sangramsingh-kss** [comment]
This was fun @kimo. My son had lot of fun playing chess on pysheets.

**Review by kimo — APPROVED** [review]
Tested and working alright. @sangramsingh-kss @laffra 
Screenshot 2024-10-07 at 12 56 17 PM

**Comment by laffra** [comment]
If you want to retry your changes on HEAD I will gladly merge. I can also see if I can merge your changes, but that will need to wait until tomorrow.

**Comment by sangramsingh-kss** [comment]
Thanks @laffra, I've resolved the conflicts.

**Review by laffra — COMMENTED** [review]
I tried this out and successfully castled! Nice addition.

**Pull request merged**
